export const CATEGORY_DEFAULT = 0x0001;
export const CATEGORY_UNRESPONSIVE = 0x0002;
export const CATEGORY_WALL = 0x0004;
export const CATEGORY_PLAYER = 0x0008;
export const CATEGORY_ITEM = 0x0016;

export const MASK_WALL = CATEGORY_DEFAULT | CATEGORY_PLAYER | CATEGORY_ITEM;
export const MASK_PLAYER = CATEGORY_DEFAULT | CATEGORY_WALL | CATEGORY_ITEM | CATEGORY_PLAYER;
export const MASK_ITEM = CATEGORY_DEFAULT | CATEGORY_WALL | CATEGORY_ITEM | CATEGORY_PLAYER;